- name: Create self-signed certificates
  command: "openssl req -new -nodes -x509 -subj \"/C={{ item.x509_country }}/ST={{ item.x509_state }}/L={{ item.x509_locality }}/O={{ item.x509_org }}/CN={{ item.x509_cn }}\" -days 3650 -keyout \"/etc/ssl/certs/{{ item }}.crt\" -out \"{{ ssl_certificates_key_path }}/{{ item }}.key\" -extensions v3_ca creates=\"{{ ssl_certificates_path }}/{{ item }}.crt\""
  with_items: "{{ ssl_certificates_selfsigned }}"
